defaults:
- imagenet_lit
  #- /attack: pgd

_target_: src.models.adv_train_lit.make_lit_module
base_class: src.models.lit_module.CrossEntropyLitModule

normalization:
    _target_: pl_bolts.transforms.dataset_normalizations.imagenet_normalization 
