# https://neptune.ai

neptune:
  _target_: pytorch_lightning.loggers.neptune.NeptuneLogger
  api_key: ${oc.env:NEPTUNE_API_TOKEN} # api key is loaded from environment variable
  project_name: your_name/template-tests
  close_after_fit: true
  offline_mode: false
  experiment_name: ${name}
  experiment_id:
  prefix: ""
