# https://wandb.ai

wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "robust-sparse-moes-debug"
  name: ${name}
  save_dir: "."
  offline: false # set True to store all logs only locally
  id: # pass correct id to resume experiment!
  # entity: ""  # set to name of your wandb team
  log_model: "all"
  prefix: ""
  job_type: "train"
  group: ""
  tags: []
